- hash.go
- json_test.go
- seq_test.go
- sql_test.go
- uuid.go
- version1.go
- version4.go
- The MustParse and MustNewUUID functions have been removed since they can be replaced simply using the new function.
```go
uuid.Must(uuid.Parse(s))
uuid.Must(uuid.NewUUID())
```
- Create NewRandom func consistent with other version constructors.The New function is kept for convenience and relies on the NewRandom function.
- This also fixes a spurious bug in the UnmarshalJSON method that prevented compiling the json.go file.
> A generic Must function

- dce.go
- marshal.go
- uuid.go
- version1.go
I found several typos and outdated bits in the godoc comments. One weird bit the spurious piece commenting UUID.Version(). I couldn't figure out what that was about but figured it was unwanted.
I also made the method receiver names consistent across the package (changing them from `u` in marshal.go). It aligns the names a bit better when looking at [godoc.org](https://godoc.org/github.com/google/uuid). It also removes some of the warnings emitted from tools like `golint`.
> Misc godoc fixes

- marshal.go
- util.go
- uuid.go
- uuid_test.go
Making xtob take two byte arguments avoids a lot of slicing.  This makes
the Parse function faster.  In addition, because so much slicing is
avoiding, duplicating the parse logic to ParseBytes resulted in the
function being faster than Parse (<1ns).
The BenchmarkParseBytesNative function has been removed (parseBytes was
identical to ParseBytes).  And a new benchmark,
BenchmarkParseBytesUnsafe, has been added to benchmark the old way of
parsing []byte (which is slightly slower than Parse and thus the new
ParseBytes implementation).
benchmark                         old ns/op     new ns/op     delta
BenchmarkUUID_MarshalJSON-4       685           667           -2.63%
BenchmarkUUID_UnmarshalJSON-4     1145          1162          +1.48%
BenchmarkParse-4                  61.6          56.5 …
> optimize internal parsing function -- avoid unsafe []byte parsing

- version4.go
> version4: Typo in 'New' doc

- node.go
Please take a look.
This looks like it was missed when the `[]byte`=>`[16]byte` change was made.
> Remove never-true conditional

- uuid.go
- uuid_test.go
`FromBytes` is a convenience constructor. It relies on `UnmarshalBinary` to create a new `UUID`. This makes creating a new `UUID` from a slice a bytes clearer in the client code without having to create a temporary variable, and more consistent with creating a slice by parsing a string.
Example:
```go
s := "f47ac10b-58cc-0372-8567-0e02b2c3d479"
suuid, err := uuid.Parse(s)
b := []byte{
0x7d, 0x44, 0x48, 0x40,
0x9d, 0xc0,
0x11, 0xd1,
0xb2, 0x45,
0x5f, 0xfd, 0xce, 0x74, 0xfa, 0xd2,
}
buuid, err := uuid.FromBytes(b)
```
----
I realize `FromBytes` is a bit of a name collision with `ParseBytes`. I am open to better suggestions for naming, of course. In fact, when discovering the library, I originally expected `ParseBytes` to perform this copy.
> add FromBytes constructor

- uuid.go
Same usability as with https://golang.org/pkg/regexp/#MustCompile
```go
var someUUID = uuid.MustParse("f47ac10b-58cc-0372-8567-0e02b2c3d479")
```
> add MustParse(), which returns an UUID or panics

- go.mod
PR adds a `go.mod` file (one-liner - package name only) and enables building and testing the package outside of GOPATH with go1.11.
> add go.mod file

- version1.go
Fixes race in NewUUID() (non-synchronized access to nodeID)
> Fix race in NewUUID()

- uuid.go
- uuid_test.go
This significantly improves the speed of failed parses due to wrong
lengths. Previously the `fmt.Errorf` call dominated, making this the
most expensive error and more expensive than successfully parsing:
BenchmarkParse-4                 29226529        36.1 ns/op
BenchmarkParseBadLength-4         6923106       174 ns/op
BenchmarkParseLen32Truncated-4   26641954        38.1 ns/op
BenchmarkParseLen36Corrupted-4   19405598        59.5 ns/op
When the formatting is not required and done on-demand, the failure per
se is much faster:
BenchmarkParse-4                 29641700        36.3 ns/op
BenchmarkParseBadLength-4        58602537        20.0 ns/op
BenchmarkParseLen32Truncated-4   30664791        43.6 ns/op
BenchmarkParseLen36Corrupted-4   18882410        61.9 ns/op
Add benchmarks for …
> Use a custom error type for invalid lengths, replacing `fmt.Errorf`

- uuid.go
Zero allocation by using non-pointer error.
related #69
```
name               old time/op    new time/op    delta
ParseBadLength-16    15.4ns ± 0%     3.5ns ± 0%   ~     (p=1.000 n=1+1)
name               old alloc/op   new alloc/op   delta
ParseBadLength-16     8.00B ± 0%     0.00B        ~     (p=1.000 n=1+1)
name               old allocs/op  new allocs/op  delta
ParseBadLength-16      1.00 ± 0%      0.00        ~     (p=1.000 n=1+1)
```
> Reduce custom error allocation

- hash.go
Error covered without change function definition
> hash.go hash error covered and linter error fixed

- version4.go
- Adds `NewString()` func, which encapsulates the more verbose `New().String()`
- We use `New().String()` for testing, and it feels ugly. Rather than adding a wrapper around `google/uuid`, figured it makes sense to add the utility method to the root package
> Add NewString Func

- uuid.go
- uuid_test.go
This change will add matcher function for custom error type invalidLengthError, it is needed to expose the matcher function as public function.
> feat: add public matcher function for custom error type invalidLengthError

- uuid.go
- uuid_test.go
- version4.go
Adds an optional randomness pool mode for Random (Version 4) UUID generation. The pool contains random bytes read from
the random number generator on demand in batches. Enabling the pool may improve the UUID generation throughput significantly.
Since the pool is stored on the Go heap, this feature may be a bad fit for security sensitive applications. That's why it's implemented as an opt-in feature.
Please treat this PR as a performance experiment.
Environment: Ubuntu 20.04, go version go1.16.2 linux/amd64, i5-8300h
`master` branch:
```
BenchmarkUUID_New-8   	          597717	        1797 ns/op	      16 B/op	       1 allocs/op
```
This branch:
```
BenchmarkUUID_New-8   	          632412	        1809 ns/op	      16 B/op	       1 allocs/op
BenchmarkUUID_NewPooled-8   	 2058459	       579.7 …
```
> Add randomness pool mode for V4 UUID

- null.go
- null_test.go
Per the discussion in #54, this introduces a `NullUUID` type to the package that works like other nullable types in the `database/sql` package. Figured I'd just get the PR out while I'm playing around in this space.
> feat(uuid): Added support for NullUUID

- .github/CODEOWNERS
- .github/workflows/tests.yaml
- .travis.yml
- README.md
* Removes `travis.yml`
* Removes Travis badge
* Adds `CODEOWNERS` set to @google/go-uuid-contributors 
* Adds Action workflow for tests
* add job to run tests over most recent three Go versions
> chore(ci): add Action-based tests

- uuid.go
Prior to this commit we used a comparison with the result of ToLower() to test for a "urn:uuid" prefix in both UUID strings and byte slices.
This commit replaces the ToLower and string comparison with both strings.EqualFold and bytes.EqualFold.
This reduces the CPU time across the board for UUIDs that start with "urn:uuid" and eliminates some allocations when parsing bytes.
The benchmark output was generated by adding "urn:uuid" to the test input.
```
goos: linux
goarch: amd64
pkg: github.com/google/uuid
cpu: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
│ /tmp/output1 │             /tmp/output2              │
│    sec/op    │    sec/op     vs base                 │
Parse-8                 35.87n ± ∞ ¹   33.75n ± ∞ ¹        ~ (p=1.000 n=1) ²
ParseBytes-8            65.10n ± ∞ ¹   35.56n ± ∞ ¹ …
```
> fix: Use .EqualFold() to parse urn prefixed UUIDs

- node_js.go
This PR corrects a typo in the comment.
> docs: fix typo node_js docs

- README.md
A little shorthand to make easier the `devExperience`.
> docs: shell format go tool command

- README.md
This PR replaces `godoc.org` with `pkg.go.dev` in README.
> docs: change godoc URL in README

- .github/workflows/apidiff.yaml
- uuid.go
Adds a GitHub Action workflow for running [`apidiff`](https://pkg.go.dev/golang.org/x/exp/apidiff). This will protect against backwards incompatible changes to this modules public API.
> chore(ci): add apidiff check for API compatibility

- .github/workflows/release.yaml
- CHANGELOG.md
- CONTRIBUTING.md
Configures the `release-please` GitHub Action for release management.
Adds a `CHANGELOG.md` for `release-please`
Update `CONTRIBUTING.md` with new tips/processes.
> chore(ci): configure release-please, update contrib

- json_test.go
I've added some test cases in JSON for documentation purposes.
Only `"00000000-0000-0000-0000-000000000000"` and `null` values are parsed without errors. Empty strings (even with `omitempty` tag) are parsed with the error `invalid UUID length`.
> chore(tests): Add json.Unmarshal test with empty value cases

- uuid_test.go
Add Go-native Fuzz tests for `Parse`, `ParseBytes`, and `FromBytes`.
Ideally, we integrate this with OSS-Fuzz instead of running in our own CI.
> chore(tests): add Fuzz tests

- uuid.go
- uuid_test.go
I often work with slices of UUIDs and want to include them in log messages. It is therefore convenient to be able to easily transform a slice of UUIDs into a slice of strings. In the interest of avoiding repeating code across many projects to accomplish this, I suggest defining a slice type in this project. 
This PR adds such a type and defines a convenience method `Strings()` on it.
This type additionally gives maintainers the opportunity to add further convenience methods; for instance one could implement the sort interface on this new type.
> feat: UUIDs slice type with Strings() convenience method

- time.go
- uuid_test.go
- version6.go
- version7.go
add uuid version6， version7
https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-03#variant_and_version_fields
recommit #138
> add uuid version 6 and 7

- .github/workflows/apidiff.yaml
- .github/workflows/tests.yaml
Closes #142 
Workflows running with the limited permissions:
- [tests.yml](https://github.com/joycebrum/uuid/actions/runs/7119437379)
- [apidiff.yml](https://github.com/joycebrum/uuid/actions/runs/7119437378)
> chore: limit permissions for github workflows

- README.md
- null_test.go
- version7.go
This PR fixes two typos I spotted in the code base and changes one link from `http` to `https` protocol.
> docs: fixing typos

- hash.go
- json_test.go
- sql_test.go
`Must(Parse("xxxx"))` is considered legacy code to forced uuid to parse because the code is pre-implementation of `Must(Parase("xxxx")) `(https://github.com/google/uuid/pull/26)
This one is simpler.
> fix: use MustParse("xxx") instead of Must(Parse("xxxx"))

- time.go
- version6.go
The timestamp part of the uuid v6 implementation is incorrect.
The only lower 60 bits of the timestamp from `GetTime` should be used,
but current implementation put entire 64-bit timestamp and overwrite the lower 4-bit part with the version ID.
Therefore, it is not field-compatible with version 1.
```
V1 timestamp
<----high---> <------mid------> <----------------low-------------->
|xxxx0000|00000000|00000000|00000000|00000000|00000000|00000000|00000000|
V6 timestamp
<----------------high--------------><-------mid------><----low---->
|xxxx0000|00000000|00000000|00000000|00000000|00000000|00000000|00000000|
Current implementation for V6 timestamp
<---------------high--------------> <-------mid----->     <----low---->
|xxxx0000|00000000|00000000|00000000|00000000|00000000|00000000|00000000| …
```
> fix incorrect timestamp in uuid v6

- util.go
- uuid_test.go
> feat: add Compare function

- README.md
- doc.go
- hash.go
- uuid.go
- version6.go
- version7.go
RFC 9562 obsoletes RFC 4122.
https://datatracker.ietf.org/doc/html/rfc9562#name-update-motivation
> docs: upd links to rfc9562

- time.go
- time_test.go
- version6.go
- version6_test.go
Hi, 
In this PR I'm addressing issue #165. I had the same problem when generating UUIDs for some older data and wanted to maintain the original date.
> feat: Generate V6 from custom time
